name: seqlike-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - pip
  - scikit-learn
  - biopython
  - numpy
  - pandas
  - pytest
  - pytest-regtest
  - weblogo
  - requests
  - pillow
  - black # for code formatting
  - mafft # necessary for multiple sequence alignemnt tests.
  - multipledispatch
  - ipykernel
  - hypothesis
  - interrogate
  - matplotlib
  - bokeh
  - python-codon-tables
  # Code quality
  - pre-commit
  - darglint
  # Docs dependencies
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  # Infrastructural
  - bump2version
  - pip:
      - mknotebooks  # for notebooks in docs
